### ISSUE TITLE
What is the organization format of the data file？

### ISSUE THREAD

**Issue by stepwhal** [likojack/ODAM#1]
Thank you for your work！I want to try to learn your code. Can you show the file organization format of the data? thank you very much!

**Comment by ChiyuanFeng** [comment]
> Thank you for your work！I want to try to learn your code. Can you show the file organization format of the data? thank you very much!

![image](https://user-images.githubusercontent.com/6463210/170196664-654c47e8-57f4-42c7-9608-3b1a3ee3296d.png)
You can replace the dataset with your dataset and organize it as picture attached. It should work.

**Comment by stepwhal** [comment]
Thank you very much！

**Comment by wf-hahaha** [comment]
@ChiyuanFeng Do you know how to train GNN？
