### ISSUE TITLE
Documentation for dataset format?

### ISSUE THREAD

**Issue by akashsharma02** [likojack/ODAM#2]
I'm trying to run the code on ScanNet, but there isn't any explanation of the data format that is required to run this. 

Specifically, how do I obtain the `meta_file` that is read in the `read_meta_file` function?

**Comment by likojack** [comment]
It comes with the original ScanNet dataset. Should be in the scene directory:
https://github.com/likojack/ODAM/blob/84ab3700676f8ede925bb5527c5236cc8c153985/src/scripts/eval_scan2cad.py#L301

**Comment by wf-hahaha** [comment]
How to train the GNN？ Can you provide training scripts？
