### ISSUE TITLE
Unable to start

### ISSUE THREAD

**Issue by AI-student-wl** [likojack/ODAM#3]
Hello, I want to reproduce the results of the paper. I put the file according to the prompts, but I can't start the code. I wonder if you can help me look at this problem. Thank you for your help

![image](https://user-images.githubusercontent.com/72002667/201318337-9d4b73bb-ace6-4857-9b06-6a122a59b986.png)

**Comment by likojack** [comment]
Hi, sorry for the belated reply.

You need to install the package learnable_primitives by running ```python setup.py install``` in the learnable_primitives folder.
